"use client";
import {useRef,useState} from "react";
type Mode="crop"|"rotate"|"flip"|"format"|"base64";
export default function AdvancedImageTool({mode,format}:{mode:Mode,format?:string}){
 const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");const [angle,setAngle]=useState(90);const [quality,setQuality]=useState(0.82);const [base64,setBase64]=useState("");const canvasRef=useRef<HTMLCanvasElement>(null);
 const save=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 const load=(f:File)=>new Promise<HTMLImageElement>((res,rej)=>{const u=URL.createObjectURL(f),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);res(i)};i.onerror=rej;i.src=u});
 const run=async()=>{if(!files.length)return;setBusy(true);setMsg("");try{
  if(mode==="base64"){const f=files[0];const r=new FileReader();r.onload=()=>{const v=String(r.result||"");setBase64(v);setMsg("Base64 data is ready below.")};r.onerror=()=>setMsg("Could not read the image.");r.readAsDataURL(f);return}
  const img=await load(files[0]);const c=canvasRef.current||document.createElement("canvas");const ctx=c.getContext("2d");if(!ctx)throw new Error();
  if(mode==="rotate"){const rad=angle*Math.PI/180,swap=Math.abs(angle)%180!==0;c.width=swap?img.height:img.width;c.height=swap?img.width:img.height;ctx.translate(c.width/2,c.height/2);ctx.rotate(rad);ctx.drawImage(img,-img.width/2,-img.height/2)}
  else if(mode==="flip"){c.width=img.width;c.height=img.height;ctx.save();if(angle===90){ctx.scale(-1,1);ctx.translate(-img.width,0)}else if(angle===270){ctx.scale(1,-1);ctx.translate(0,-img.height)}else{ctx.scale(-1,-1);ctx.translate(-img.width,-img.height)}ctx.drawImage(img,0,0);ctx.restore()}
  else if(mode==="crop"){const w=Math.min(img.width,Number((document.getElementById("cropw") as HTMLInputElement)?.value)||img.width);const h=Math.min(img.height,Number((document.getElementById("croph") as HTMLInputElement)?.value)||img.height);c.width=w;c.height=h;ctx.drawImage(img,Math.max(0,(img.width-w)/2),Math.max(0,(img.height-h)/2),w,h,0,0,w,h)}
  else {c.width=img.width;c.height=img.height;ctx.drawImage(img,0,0)}
  const mime=format==="png"?"image/png":format==="webp"?"image/webp":"image/jpeg";c.toBlob(b=>{if(b)save(b,`converted.${format||"jpg"}`)},mime,quality);setMsg("Done — your image was created in your browser.");
 }catch{setMsg("Could not process this image. Check the file format and try again.")}finally{setBusy(false)}};
 return <div><div className="drop"><h2>{mode==="crop"?"Crop Image":mode==="rotate"?"Rotate Image":mode==="flip"?"Flip Image":mode==="base64"?"Image to Base64":`Convert to ${format?.toUpperCase()}`}</h2><p>Processing happens locally in your browser.</p><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setFiles(Array.from(e.target.files||[]));setBase64("");setMsg("")}}/>{mode==="rotate"&&<div className="controls"><label>Angle <select value={angle} onChange={e=>setAngle(Number(e.target.value))}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></label></div>}{mode==="flip"&&<div className="controls"><label>Flip <select value={angle} onChange={e=>setAngle(Number(e.target.value))}><option value="90">Horizontal</option><option value="270">Vertical</option><option value="180">Both</option></select></label></div>}{mode==="crop"&&<div className="controls"><label>Width <input id="cropw" type="number" min="1" placeholder="px"/></label><label>Height <input id="croph" type="number" min="1" placeholder="px"/></label></div>}{mode==="format"&&<div className="controls"><label>Quality <input type="range" min="0.4" max="1" step="0.02" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label></div>}<button className="btn" disabled={!files.length||busy} onClick={run}>{busy?"Processing…":"Process image"}</button></div>{base64&&<textarea style={{width:"100%",minHeight:180,marginTop:16}} value={base64} readOnly/>}{msg&&<div className="notice">{msg}</div>}<canvas ref={canvasRef} style={{display:"none"}}/></div>
}