"use client";
import {useState} from "react";import {PDFDocument,degrees} from "pdf-lib";import JSZip from "jszip";import FilePicker from "./FilePicker";
export default function FileTool({mode}:{mode:"merge"|"split"|"rotate"|"imagepdf"}) {
 const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
 const pick=(next:File[])=>{setFiles(next);setMsg("")};
 const save=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const makeBlob=(data:Uint8Array,type:string)=>{const buffer=new ArrayBuffer(data.byteLength);new Uint8Array(buffer).set(data);return new Blob([buffer],{type})};
 const run=async()=>{if(!files.length)return;setBusy(true);setMsg("");try{
  if(mode==="imagepdf"){const pdf=await PDFDocument.create();for(const f of files){const ext=f.name.toLowerCase().split(".").pop();if(!["image/jpeg","image/png"].includes(f.type)&&!["jpg","jpeg","png"].includes(ext||""))throw new Error();const b=await f.arrayBuffer();const isJpg=f.type==="image/jpeg"||["jpg","jpeg"].includes(ext||"");const img=isJpg?await pdf.embedJpg(b):await pdf.embedPng(b);const page=pdf.addPage([595,842]);const scale=Math.min(555/img.width,802/img.height);page.drawImage(img,{x:(595-img.width*scale)/2,y:(842-img.height*scale)/2,width:img.width*scale,height:img.height*scale});}save(makeBlob(await pdf.save(),"application/pdf"),"images.pdf");}
  else if(mode==="merge"){if(files.length<2)throw new Error();const out=await PDFDocument.create();for(const f of files){const src=await PDFDocument.load(await f.arrayBuffer());const pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p));}save(makeBlob(await out.save(),"application/pdf"),"merged.pdf");}
  else if(mode==="split"){const src=await PDFDocument.load(await files[0].arrayBuffer());const zip=new JSZip();for(let i=0;i<src.getPageCount();i++){const out=await PDFDocument.create();const [p]=await out.copyPages(src,[i]);out.addPage(p);zip.file(`page-${i+1}.pdf`,await out.save());}save(await zip.generateAsync({type:"blob"}),"split-pages.zip");}
  else {const src=await PDFDocument.load(await files[0].arrayBuffer());src.getPages().forEach(p=>p.setRotation(degrees((p.getRotation().angle+90)%360)));save(makeBlob(await src.save(),"application/pdf"),"rotated.pdf");}
  setMsg("Done — your file was created in your browser.");}catch{setMsg("Could not process this file. Check the format, file count and PDF validity, then try again.")}finally{setBusy(false)}};
 const accept=mode==="imagepdf"?".jpg,.jpeg,.png":".pdf";const title={merge:"Merge PDF",split:"Split PDF",rotate:"Rotate PDF",imagepdf:"Images to PDF"}[mode];
 return <div><div className="drop"><h2>{title}</h2><p>Select your files. Processing happens locally in your browser.</p><FilePicker accept={accept} multiple={mode==="merge"||mode==="imagepdf"} files={files} onChange={pick}/>{files.length>0&&<p className="filecount">{files.length} file(s) selected</p>}<button className="btn" disabled={!files.length||busy||(mode==="merge"&&files.length<2)} onClick={run}>{busy?"Processing…":mode==="split"?"Create ZIP":"Process files"}</button></div>{files.length>0&&<div className="files">{files.map((f,i)=><div className="file" key={i}><span>{f.name}</span><span>{Math.max(1,Math.round(f.size/1024))} KB</span></div>)}</div>}{msg&&<div className="notice">{msg}</div>}</div>
}