import Link from "next/link";import type {ElementType} from "react";import AdSlot from "../../components/AdSlot";
import {FileText,Scissors,RotateCw,Trash2,Files,FilePlus2,ListOrdered,Stamp,Hash,FileCog,FilePlus,FileImage,Images,Maximize2,Minimize2,RefreshCw,Crop,RotateCcw,FlipHorizontal2,FileType,Image,ImagePlus,Code2,Braces,FileCode2,Palette,FileDown} from "lucide-react";
type Tool=[string,string,ElementType];const groups:[string,Tool[]][]=[
["PDF tools",[
["Merge PDF","/merge-pdf/",Files],["Split PDF","/split-pdf/",Scissors],["Rotate PDF","/rotate-pdf/",RotateCw],["Delete PDF Pages","/delete-pages-from-pdf/",Trash2],["Extract PDF Pages","/extract-pages-from-pdf/",FileDown],["Add Pages to PDF","/add-pages-to-pdf/",FilePlus2],["Reorder PDF Pages","/reorder-pdf/",ListOrdered],["Watermark PDF","/watermark-pdf/",Stamp],["Number PDF Pages","/number-pdf-pages/",Hash],["Edit PDF Metadata","/pdf-metadata/",FileCog],["Add Blank Pages","/add-blank-pages-to-pdf/",FilePlus],["JPG to PDF","/jpg-to-pdf/",FileImage],["PNG to PDF","/png-to-pdf/",ImagePlus],["Images to PDF","/image-to-pdf/",Images],["PDF to JPG","/pdf-to-jpg/",FileImage],["PDF to PNG","/pdf-to-png/",FileImage]
]],
["Image tools",[
["Resize Image","/resize-image/",Maximize2],["Compress Image","/compress-image/",Minimize2],["Convert Image","/convert-image/",RefreshCw],["Crop Image","/crop-image/",Crop],["Rotate Image","/rotate-image/",RotateCcw],["Flip Image","/flip-image/",FlipHorizontal2],["JPG to PNG","/jpg-to-png/",FileType],["PNG to JPG","/png-to-jpg/",FileType],["JPG to WebP","/jpg-to-webp/",FileType],["PNG to WebP","/png-to-webp/",FileType],["WebP to JPG","/webp-to-jpg/",FileType],["WebP to PNG","/webp-to-png/",FileType]
]],
["Developer image utilities",[
["Image to Base64","/image-to-base64/",Code2],["Base64 to Image","/base64-to-image/",Image],["Image to HTML","/image-to-html/",FileCode2],["Image to Markdown","/image-to-markdown/",Braces],["Image to CSS","/image-to-css/",Palette]
]]
];
export const metadata={title:"All PDF & Image Tools",description:"Browse all 33 free PDF and image utilities by workflow."};
export default function Page(){const total=groups.reduce((n,[,items])=>n+(items as unknown[]).length,0);return <main className="toolpage"><Link href="/">← Home</Link><h1>All PDF &amp; Image Tools</h1><p className="lead">{total} focused browser-based tools, grouped by workflow.</p><AdSlot/>{groups.map(([name,items])=><section id={(name as string).replace(/[^a-z]+/gi,"-").toLowerCase()} className="content" key={name as string}><div className="catalogSectionHead"><div><span className="sectiontag">{name==="PDF tools"?"DOCUMENTS":name==="Image tools"?"IMAGES":"DEVELOPER"}</span><h2>{name}</h2></div><span className="catalogCount">{(items as unknown[]).length} tools</span></div><div className="catalogGrid">{(items as Tool[]).map(([t,u,Icon])=><Link className="catalogCard" href={u} key={t}><span className="catalogIcon"><Icon size={22} strokeWidth={2}/></span><span className="catalogInfo"><strong>{t}</strong><small>Open tool →</small></span></Link>)}</div></section>)}</main>}
